name: Verify commit
on: [push]
jobs:
  Check-Assemble-BuildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./gradlew check assemble buildImage
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
      - run: echo "ğŸ This job's status is ${{ job.status }}."
